Fix lvm issues when reusing minion pool for os morphing and disk replication
We're disabling lvm udev rules as part of the backup writer setup
in order to prevent the migrated volumes from being automatically
mounted on the replicator vm.

Meanwhile, we're always trying to install lvm2 when setting up
the osmorphing mount tools. The post-installation hooks fail
because of the lvm related changes that we made.

```
    Traceback (most recent call last):
      File "/var/log/coriolis/coriolis/coriolis/worker/rpc/server.py", line 699, in _task_process
        task_result = task_runner.run(
      File "/var/log/coriolis/coriolis/coriolis/tasks/base.py", line 118, in run
        result = self._run(
      File "/var/log/coriolis/coriolis/coriolis/tasks/osmorphing_tasks.py", line 76, in _run
        osmorphing_manager.morph_image(
      File "/var/log/coriolis/coriolis/coriolis/osmorphing/manager.py", line 152, in morph_image
        raise exception.CoriolisException(
    coriolis.exception.CoriolisException: Failed to set up the minion machine for OSMorphing. This may be due to an incompatibility between the OS image used for the OSMorphing minion machine and the VM undergoing
     OSMorphing. Error was: Command "sudo env DEBIAN_FRONTEND=noninteractive apt-get -o DPkg::Lock::Timeout=600 install lvm2 psmisc cryptsetup -y" failed on host '45.141.74.37:22' with exit code: 100
    stdout: Reading package lists...
```

To avoid this, we'll check if lvm2 is already installed and skip
the install command if it's already available.